### ISSUE TITLE
sendExportRequest is not defined

### ISSUE THREAD

**Issue by ishu3101** [jsonresume/resume-cli#232]
When I run `resume export index.html --theme kendall`, after updating resume-cli from **version 0.4.14** to the **latest version (0.4.18**), I'm getting **sendExportRequest is not defined** error message.

```
/usr/local/lib/node_modules/resume-cli/lib/export-resume/index.js:31
      sendExportRequest(resumeJson, fileName, theme, format, function() {
      ^

ReferenceError: sendExportRequest is not defined
    at Object.exportResume (/usr/local/lib/node_modules/resume-cli/lib/export-resume/index.js:31:7)
    at Command.<anonymous> (/usr/local/lib/node_modules/resume-cli/index.js:69:11)
    at Command.listener (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:458:21)
    at /usr/local/lib/node_modules/resume-cli/index.js:88:11
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:550:17
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:544:17
    at _arrayEach (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:543:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by voncay** [comment]
I had the same issue and the latest PR fixed it for me.  
Try a full re-install with `npm install -g resume-cli`.

**Comment by benhassara** [comment]
If you run `resume --version` what does it output? #231 should have removed the call to `sendExportRequest`.

**Comment by ishu3101** [comment]
I'm running the latest version v0.4.18 and node v4.2.2. I was now getting **Error: Cannot find module 'jsonresume-theme-kendall'**. Running `npm install -g jsonresume-theme-kendall` before exporting fixed the issue.

What themes are supported by default (ie without having to install any other module like the kendall theme module) when you run `resume export `?

Also, is the kendall theme removed from the default themes that are available when you install resume-cli as it was working in version v0.4.14?

**Comment by thomasdavis** [comment]
Install the theme globally as a temp fix

**Comment by benhassara** [comment]
@ishu3101 The default theme is `jsonresume-theme-flat`, and the others that ship with the CLI right now are `modern` and `crisp`. You can see them listed by running `resume --help`. The ones that ship you can specify like `resume export resume.html -t modern`

**Comment by ishu3101** [comment]
I see that the traditional theme has been removed from the latest version. Why was it removed?

**Comment by astephen2** [comment]
Sorry I've been away for so long - long vacation.

A simple `npm install <theme-name>` should provide the theme for the folder you're in. As long as the theme is installed in some way, you should be able to export. The original export seemed to rely on the theme packages being installed all on a server.

**Comment by benhassara** [comment]
@ishu3101 It was removed because I couldn't find an NPM package for it, so there wasn't a way for me to bundle the theme as a dependency with the CLI. Previously, all export requests were sent to the server to compile the theme and resume data together. This is no longer the case as of #222.

**Comment by thomasdavis** [comment]
Pretty sure this issue is fixed. Have also added a notice to install themes locally for exporting.
